use_frameworks!

platform :ios, '9.0'

target 'GFCommonLib_Example' do
  pod 'GFCommonLib', :path => '../'

  target 'GFCommonLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
